// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace SpiritDash
{
public static class GPGSIds
{
        public const string achievement_scroodge_award = "CgkIjc30_rwdEAIQDw"; // <GPGSID>
        public const string achievement_mobile_master_race_award = "CgkIjc30_rwdEAIQBg"; // <GPGSID>
        public const string achievement_one_punch_man = "CgkIjc30_rwdEAIQDg"; // <GPGSID>
        public const string achievement_dont_drive_while_playing_this_award = "CgkIjc30_rwdEAIQBQ"; // <GPGSID>
        public const string achievement_young_blood = "CgkIjc30_rwdEAIQAw"; // <GPGSID>
        public const string achievement_bank_man = "CgkIjc30_rwdEAIQCw"; // <GPGSID>
        public const string achievement_youll_probably_get_fired_from_work = "CgkIjc30_rwdEAIQBA"; // <GPGSID>
        public const string achievement_bruce_wayne_pimpin = "CgkIjc30_rwdEAIQDQ"; // <GPGSID>
        public const string achievement_business_class_soul = "CgkIjc30_rwdEAIQCg"; // <GPGSID>
        public const string achievement_coin_doubler = "CgkIjc30_rwdEAIQFg"; // <GPGSID>
        public const string achievement_wave_man = "CgkIjc30_rwdEAIQEQ"; // <GPGSID>
        public const string achievement_pumpkin_pie = "CgkIjc30_rwdEAIQGA"; // <GPGSID>
        public const string achievement_money_grows_on_spirit_trees = "CgkIjc30_rwdEAIQAQ"; // <GPGSID>
        public const string achievement_you_deserve_a_snack = "CgkIjc30_rwdEAIQCA"; // <GPGSID>
        public const string achievement_gold_plate = "CgkIjc30_rwdEAIQCQ"; // <GPGSID>
        public const string achievement_spirit_runner = "CgkIjc30_rwdEAIQEg"; // <GPGSID>
        public const string achievement_starving_artist = "CgkIjc30_rwdEAIQEA"; // <GPGSID>
        public const string achievement_money_money_money = "CgkIjc30_rwdEAIQAg"; // <GPGSID>
        public const string leaderboard_topscore = "CgkIjc30_rwdEAIQAA"; // <GPGSID>
        public const string achievement_buffer_overflow = "CgkIjc30_rwdEAIQFQ"; // <GPGSID>
        public const string achievement_wave_musician = "CgkIjc30_rwdEAIQEw"; // <GPGSID>
        public const string achievement_zombie_apocalypse_survivor = "CgkIjc30_rwdEAIQFA"; // <GPGSID>
        public const string achievement_elon_musk_level = "CgkIjc30_rwdEAIQDA"; // <GPGSID>
        public const string achievement_lepricon_gold = "CgkIjc30_rwdEAIQBw"; // <GPGSID>

}
}
